// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: analytics-service/analytics-service.proto

package analyticsservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedbackService_UpsertFeedback_FullMethodName   = "/analytics.v1.FeedbackService/UpsertFeedback"
	FeedbackService_RemoveFeedback_FullMethodName   = "/analytics.v1.FeedbackService/RemoveFeedback"
	FeedbackService_GetFeedback_FullMethodName      = "/analytics.v1.FeedbackService/GetFeedback"
	FeedbackService_ListUserFeedback_FullMethodName = "/analytics.v1.FeedbackService/ListUserFeedback"
)

// FeedbackServiceClient is the client API for FeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedbackServiceClient interface {
	UpsertFeedback(ctx context.Context, in *UpsertFeedbackRequest, opts ...grpc.CallOption) (*UpsertFeedbackResponse, error)
	RemoveFeedback(ctx context.Context, in *RemoveFeedbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetFeedback(ctx context.Context, in *GetFeedbackRequest, opts ...grpc.CallOption) (*GetFeedbackResponse, error)
	ListUserFeedback(ctx context.Context, in *ListUserFeedbackRequest, opts ...grpc.CallOption) (*ListUserFeedbackResponse, error)
}

type feedbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedbackServiceClient(cc grpc.ClientConnInterface) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) UpsertFeedback(ctx context.Context, in *UpsertFeedbackRequest, opts ...grpc.CallOption) (*UpsertFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertFeedbackResponse)
	err := c.cc.Invoke(ctx, FeedbackService_UpsertFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) RemoveFeedback(ctx context.Context, in *RemoveFeedbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedbackService_RemoveFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetFeedback(ctx context.Context, in *GetFeedbackRequest, opts ...grpc.CallOption) (*GetFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedbackResponse)
	err := c.cc.Invoke(ctx, FeedbackService_GetFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) ListUserFeedback(ctx context.Context, in *ListUserFeedbackRequest, opts ...grpc.CallOption) (*ListUserFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserFeedbackResponse)
	err := c.cc.Invoke(ctx, FeedbackService_ListUserFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServiceServer is the server API for FeedbackService service.
// All implementations must embed UnimplementedFeedbackServiceServer
// for forward compatibility.
type FeedbackServiceServer interface {
	UpsertFeedback(context.Context, *UpsertFeedbackRequest) (*UpsertFeedbackResponse, error)
	RemoveFeedback(context.Context, *RemoveFeedbackRequest) (*emptypb.Empty, error)
	GetFeedback(context.Context, *GetFeedbackRequest) (*GetFeedbackResponse, error)
	ListUserFeedback(context.Context, *ListUserFeedbackRequest) (*ListUserFeedbackResponse, error)
	mustEmbedUnimplementedFeedbackServiceServer()
}

// UnimplementedFeedbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedbackServiceServer struct{}

func (UnimplementedFeedbackServiceServer) UpsertFeedback(context.Context, *UpsertFeedbackRequest) (*UpsertFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) RemoveFeedback(context.Context, *RemoveFeedbackRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) GetFeedback(context.Context, *GetFeedbackRequest) (*GetFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) ListUserFeedback(context.Context, *ListUserFeedbackRequest) (*ListUserFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) mustEmbedUnimplementedFeedbackServiceServer() {}
func (UnimplementedFeedbackServiceServer) testEmbeddedByValue()                         {}

// UnsafeFeedbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedbackServiceServer will
// result in compilation errors.
type UnsafeFeedbackServiceServer interface {
	mustEmbedUnimplementedFeedbackServiceServer()
}

func RegisterFeedbackServiceServer(s grpc.ServiceRegistrar, srv FeedbackServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedbackService_ServiceDesc, srv)
}

func _FeedbackService_UpsertFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).UpsertFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_UpsertFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).UpsertFeedback(ctx, req.(*UpsertFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_RemoveFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).RemoveFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_RemoveFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).RemoveFeedback(ctx, req.(*RemoveFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_GetFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetFeedback(ctx, req.(*GetFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_ListUserFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).ListUserFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_ListUserFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).ListUserFeedback(ctx, req.(*ListUserFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedbackService_ServiceDesc is the grpc.ServiceDesc for FeedbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertFeedback",
			Handler:    _FeedbackService_UpsertFeedback_Handler,
		},
		{
			MethodName: "RemoveFeedback",
			Handler:    _FeedbackService_RemoveFeedback_Handler,
		},
		{
			MethodName: "GetFeedback",
			Handler:    _FeedbackService_GetFeedback_Handler,
		},
		{
			MethodName: "ListUserFeedback",
			Handler:    _FeedbackService_ListUserFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics-service/analytics-service.proto",
}

const (
	RecommendationService_GenerateRecommendations_FullMethodName    = "/analytics.v1.RecommendationService/GenerateRecommendations"
	RecommendationService_MarkInteraction_FullMethodName            = "/analytics.v1.RecommendationService/MarkInteraction"
	RecommendationService_ResetRecommendationHistory_FullMethodName = "/analytics.v1.RecommendationService/ResetRecommendationHistory"
	RecommendationService_GetRecommendationHistory_FullMethodName   = "/analytics.v1.RecommendationService/GetRecommendationHistory"
)

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationServiceClient interface {
	GenerateRecommendations(ctx context.Context, in *GenerateRecommendationsRequest, opts ...grpc.CallOption) (*GenerateRecommendationsResponse, error)
	MarkInteraction(ctx context.Context, in *MarkInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetRecommendationHistory(ctx context.Context, in *ResetRecommendationHistoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRecommendationHistory(ctx context.Context, in *GetRecommendationHistoryRequest, opts ...grpc.CallOption) (*GetRecommendationHistoryResponse, error)
}

type recommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServiceClient(cc grpc.ClientConnInterface) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) GenerateRecommendations(ctx context.Context, in *GenerateRecommendationsRequest, opts ...grpc.CallOption) (*GenerateRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GenerateRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) MarkInteraction(ctx context.Context, in *MarkInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecommendationService_MarkInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) ResetRecommendationHistory(ctx context.Context, in *ResetRecommendationHistoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecommendationService_ResetRecommendationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetRecommendationHistory(ctx context.Context, in *GetRecommendationHistoryRequest, opts ...grpc.CallOption) (*GetRecommendationHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationHistoryResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetRecommendationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
// All implementations must embed UnimplementedRecommendationServiceServer
// for forward compatibility.
type RecommendationServiceServer interface {
	GenerateRecommendations(context.Context, *GenerateRecommendationsRequest) (*GenerateRecommendationsResponse, error)
	MarkInteraction(context.Context, *MarkInteractionRequest) (*emptypb.Empty, error)
	ResetRecommendationHistory(context.Context, *ResetRecommendationHistoryRequest) (*emptypb.Empty, error)
	GetRecommendationHistory(context.Context, *GetRecommendationHistoryRequest) (*GetRecommendationHistoryResponse, error)
	mustEmbedUnimplementedRecommendationServiceServer()
}

// UnimplementedRecommendationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationServiceServer struct{}

func (UnimplementedRecommendationServiceServer) GenerateRecommendations(context.Context, *GenerateRecommendationsRequest) (*GenerateRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) MarkInteraction(context.Context, *MarkInteractionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkInteraction not implemented")
}
func (UnimplementedRecommendationServiceServer) ResetRecommendationHistory(context.Context, *ResetRecommendationHistoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetRecommendationHistory not implemented")
}
func (UnimplementedRecommendationServiceServer) GetRecommendationHistory(context.Context, *GetRecommendationHistoryRequest) (*GetRecommendationHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendationHistory not implemented")
}
func (UnimplementedRecommendationServiceServer) mustEmbedUnimplementedRecommendationServiceServer() {}
func (UnimplementedRecommendationServiceServer) testEmbeddedByValue()                               {}

// UnsafeRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServiceServer will
// result in compilation errors.
type UnsafeRecommendationServiceServer interface {
	mustEmbedUnimplementedRecommendationServiceServer()
}

func RegisterRecommendationServiceServer(s grpc.ServiceRegistrar, srv RecommendationServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationService_ServiceDesc, srv)
}

func _RecommendationService_GenerateRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GenerateRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GenerateRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GenerateRecommendations(ctx, req.(*GenerateRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_MarkInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).MarkInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_MarkInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).MarkInteraction(ctx, req.(*MarkInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_ResetRecommendationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRecommendationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).ResetRecommendationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_ResetRecommendationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).ResetRecommendationHistory(ctx, req.(*ResetRecommendationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetRecommendationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetRecommendationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetRecommendationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetRecommendationHistory(ctx, req.(*GetRecommendationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationService_ServiceDesc is the grpc.ServiceDesc for RecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRecommendations",
			Handler:    _RecommendationService_GenerateRecommendations_Handler,
		},
		{
			MethodName: "MarkInteraction",
			Handler:    _RecommendationService_MarkInteraction_Handler,
		},
		{
			MethodName: "ResetRecommendationHistory",
			Handler:    _RecommendationService_ResetRecommendationHistory_Handler,
		},
		{
			MethodName: "GetRecommendationHistory",
			Handler:    _RecommendationService_GetRecommendationHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics-service/analytics-service.proto",
}
