// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: analytics-service/analytics-service.proto

package analyticsservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	movieservicev1 "github.com/BigMoneyBigSuccess/cineMate/proto/movie-service/movieservicev1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,6,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *Feedback) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Feedback) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Feedback) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

// feedback_id: omit to create a new record; provide to target an existing one.
type UpsertFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    *string                `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3,oneof" json:"feedback_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,6,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFeedbackRequest) Reset() {
	*x = UpsertFeedbackRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFeedbackRequest) ProtoMessage() {}

func (x *UpsertFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFeedbackRequest.ProtoReflect.Descriptor instead.
func (*UpsertFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertFeedbackRequest) GetFeedbackId() string {
	if x != nil && x.FeedbackId != nil {
		return *x.FeedbackId
	}
	return ""
}

func (x *UpsertFeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertFeedbackRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *UpsertFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpsertFeedbackRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpsertFeedbackRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type UpsertFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFeedbackResponse) Reset() {
	*x = UpsertFeedbackResponse{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFeedbackResponse) ProtoMessage() {}

func (x *UpsertFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFeedbackResponse.ProtoReflect.Descriptor instead.
func (*UpsertFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertFeedbackResponse) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

type RemoveFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFeedbackRequest) Reset() {
	*x = RemoveFeedbackRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFeedbackRequest) ProtoMessage() {}

func (x *RemoveFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFeedbackRequest.ProtoReflect.Descriptor instead.
func (*RemoveFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFeedbackRequest) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

type GetFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackRequest) Reset() {
	*x = GetFeedbackRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackRequest) ProtoMessage() {}

func (x *GetFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedbackRequest) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

type GetFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *Feedback              `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackResponse) Reset() {
	*x = GetFeedbackResponse{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackResponse) ProtoMessage() {}

func (x *GetFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFeedbackResponse) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type ListUserFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFeedbackRequest) Reset() {
	*x = ListUserFeedbackRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFeedbackRequest) ProtoMessage() {}

func (x *ListUserFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFeedbackRequest.ProtoReflect.Descriptor instead.
func (*ListUserFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserFeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      []*Feedback            `protobuf:"bytes,1,rep,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFeedbackResponse) Reset() {
	*x = ListUserFeedbackResponse{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFeedbackResponse) ProtoMessage() {}

func (x *ListUserFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFeedbackResponse.ProtoReflect.Descriptor instead.
func (*ListUserFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserFeedbackResponse) GetFeedback() []*Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type Recommendation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"` // needed for MarkInteraction
	Movie            *movieservicev1.Movie  `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Strategy         string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	AiResponse       *string                `protobuf:"bytes,4,opt,name=ai_response,json=aiResponse,proto3,oneof" json:"ai_response,omitempty"` // raw AI text; set only for ai_model_based strategy
	Rank             int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	GeneratedAt      int64                  `protobuf:"varint,6,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // Unix timestamp (seconds)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{8}
}

func (x *Recommendation) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *Recommendation) GetMovie() *movieservicev1.Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *Recommendation) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Recommendation) GetAiResponse() string {
	if x != nil && x.AiResponse != nil {
		return *x.AiResponse
	}
	return ""
}

func (x *Recommendation) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Recommendation) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

// limit: 0 means use server default.
// strategy: one of preference_profile_based | genres_based | actors_based |
//
//	directors_based | ai_model_based.
//	Empty string falls back to preference_profile_based.
type GenerateRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRecommendationsRequest) Reset() {
	*x = GenerateRecommendationsRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecommendationsRequest) ProtoMessage() {}

func (x *GenerateRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GenerateRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateRecommendationsRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *GenerateRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GenerateRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRecommendationsResponse) Reset() {
	*x = GenerateRecommendationsResponse{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecommendationsResponse) ProtoMessage() {}

func (x *GenerateRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GenerateRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// interaction: "click" | "dismiss"
type MarkInteractionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Interaction      string                 `protobuf:"bytes,2,opt,name=interaction,proto3" json:"interaction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarkInteractionRequest) Reset() {
	*x = MarkInteractionRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkInteractionRequest) ProtoMessage() {}

func (x *MarkInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkInteractionRequest.ProtoReflect.Descriptor instead.
func (*MarkInteractionRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{11}
}

func (x *MarkInteractionRequest) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *MarkInteractionRequest) GetInteraction() string {
	if x != nil {
		return x.Interaction
	}
	return ""
}

type ResetRecommendationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRecommendationHistoryRequest) Reset() {
	*x = ResetRecommendationHistoryRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRecommendationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRecommendationHistoryRequest) ProtoMessage() {}

func (x *ResetRecommendationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRecommendationHistoryRequest.ProtoReflect.Descriptor instead.
func (*ResetRecommendationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{12}
}

func (x *ResetRecommendationHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// limit: number of most-recent recommendations to return; 0 means use server default.
type GetRecommendationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationHistoryRequest) Reset() {
	*x = GetRecommendationHistoryRequest{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationHistoryRequest) ProtoMessage() {}

func (x *GetRecommendationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecommendationHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationHistoryRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *GetRecommendationHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendationHistoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationHistoryResponse) Reset() {
	*x = GetRecommendationHistoryResponse{}
	mi := &file_analytics_service_analytics_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationHistoryResponse) ProtoMessage() {}

func (x *GetRecommendationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_analytics_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_analytics_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecommendationHistoryResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_analytics_service_analytics_service_proto protoreflect.FileDescriptor

const file_analytics_service_analytics_service_proto_rawDesc = "" +
	"\n" +
	")analytics-service/analytics-service.proto\x12\fanalytics.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a!movie-service/movie_service.proto\"\xc7\x01\n" +
	"\bFeedback\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x06 \x01(\tH\x01R\acontent\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"\xe9\x01\n" +
	"\x15UpsertFeedbackRequest\x12$\n" +
	"\vfeedback_id\x18\x01 \x01(\tH\x00R\n" +
	"feedbackId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x06 \x01(\tH\x02R\acontent\x88\x01\x01B\x0e\n" +
	"\f_feedback_idB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"9\n" +
	"\x16UpsertFeedbackResponse\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\"8\n" +
	"\x15RemoveFeedbackRequest\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\"5\n" +
	"\x12GetFeedbackRequest\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\"I\n" +
	"\x13GetFeedbackResponse\x122\n" +
	"\bfeedback\x18\x01 \x01(\v2\x16.analytics.v1.FeedbackR\bfeedback\"2\n" +
	"\x17ListUserFeedbackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x18ListUserFeedbackResponse\x122\n" +
	"\bfeedback\x18\x01 \x03(\v2\x16.analytics.v1.FeedbackR\bfeedback\"\xf4\x01\n" +
	"\x0eRecommendation\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12,\n" +
	"\x05movie\x18\x02 \x01(\v2\x16.movieservice.v1.MovieR\x05movie\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12$\n" +
	"\vai_response\x18\x04 \x01(\tH\x00R\n" +
	"aiResponse\x88\x01\x01\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12!\n" +
	"\fgenerated_at\x18\x06 \x01(\x03R\vgeneratedAtB\x0e\n" +
	"\f_ai_response\"k\n" +
	"\x1eGenerateRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"i\n" +
	"\x1fGenerateRecommendationsResponse\x12F\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1c.analytics.v1.RecommendationR\x0frecommendations\"g\n" +
	"\x16MarkInteractionRequest\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12 \n" +
	"\vinteraction\x18\x02 \x01(\tR\vinteraction\"<\n" +
	"!ResetRecommendationHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"l\n" +
	"\x1fGetRecommendationHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"j\n" +
	" GetRecommendationHistoryResponse\x12F\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1c.analytics.v1.RecommendationR\x0frecommendations2\xf4\x02\n" +
	"\x0fFeedbackService\x12[\n" +
	"\x0eUpsertFeedback\x12#.analytics.v1.UpsertFeedbackRequest\x1a$.analytics.v1.UpsertFeedbackResponse\x12M\n" +
	"\x0eRemoveFeedback\x12#.analytics.v1.RemoveFeedbackRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\vGetFeedback\x12 .analytics.v1.GetFeedbackRequest\x1a!.analytics.v1.GetFeedbackResponse\x12a\n" +
	"\x10ListUserFeedback\x12%.analytics.v1.ListUserFeedbackRequest\x1a&.analytics.v1.ListUserFeedbackResponse2\xc2\x03\n" +
	"\x15RecommendationService\x12v\n" +
	"\x17GenerateRecommendations\x12,.analytics.v1.GenerateRecommendationsRequest\x1a-.analytics.v1.GenerateRecommendationsResponse\x12O\n" +
	"\x0fMarkInteraction\x12$.analytics.v1.MarkInteractionRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x1aResetRecommendationHistory\x12/.analytics.v1.ResetRecommendationHistoryRequest\x1a\x16.google.protobuf.Empty\x12y\n" +
	"\x18GetRecommendationHistory\x12-.analytics.v1.GetRecommendationHistoryRequest\x1a..analytics.v1.GetRecommendationHistoryResponseB?Z=proto/analytics-service/analyticsservicev1;analyticsservicev1b\x06proto3"

var (
	file_analytics_service_analytics_service_proto_rawDescOnce sync.Once
	file_analytics_service_analytics_service_proto_rawDescData []byte
)

func file_analytics_service_analytics_service_proto_rawDescGZIP() []byte {
	file_analytics_service_analytics_service_proto_rawDescOnce.Do(func() {
		file_analytics_service_analytics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_service_proto_rawDesc), len(file_analytics_service_analytics_service_proto_rawDesc)))
	})
	return file_analytics_service_analytics_service_proto_rawDescData
}

var file_analytics_service_analytics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_analytics_service_analytics_service_proto_goTypes = []any{
	(*Feedback)(nil),                          // 0: analytics.v1.Feedback
	(*UpsertFeedbackRequest)(nil),             // 1: analytics.v1.UpsertFeedbackRequest
	(*UpsertFeedbackResponse)(nil),            // 2: analytics.v1.UpsertFeedbackResponse
	(*RemoveFeedbackRequest)(nil),             // 3: analytics.v1.RemoveFeedbackRequest
	(*GetFeedbackRequest)(nil),                // 4: analytics.v1.GetFeedbackRequest
	(*GetFeedbackResponse)(nil),               // 5: analytics.v1.GetFeedbackResponse
	(*ListUserFeedbackRequest)(nil),           // 6: analytics.v1.ListUserFeedbackRequest
	(*ListUserFeedbackResponse)(nil),          // 7: analytics.v1.ListUserFeedbackResponse
	(*Recommendation)(nil),                    // 8: analytics.v1.Recommendation
	(*GenerateRecommendationsRequest)(nil),    // 9: analytics.v1.GenerateRecommendationsRequest
	(*GenerateRecommendationsResponse)(nil),   // 10: analytics.v1.GenerateRecommendationsResponse
	(*MarkInteractionRequest)(nil),            // 11: analytics.v1.MarkInteractionRequest
	(*ResetRecommendationHistoryRequest)(nil), // 12: analytics.v1.ResetRecommendationHistoryRequest
	(*GetRecommendationHistoryRequest)(nil),   // 13: analytics.v1.GetRecommendationHistoryRequest
	(*GetRecommendationHistoryResponse)(nil),  // 14: analytics.v1.GetRecommendationHistoryResponse
	(*movieservicev1.Movie)(nil),              // 15: movieservice.v1.Movie
	(*emptypb.Empty)(nil),                     // 16: google.protobuf.Empty
}
var file_analytics_service_analytics_service_proto_depIdxs = []int32{
	0,  // 0: analytics.v1.GetFeedbackResponse.feedback:type_name -> analytics.v1.Feedback
	0,  // 1: analytics.v1.ListUserFeedbackResponse.feedback:type_name -> analytics.v1.Feedback
	15, // 2: analytics.v1.Recommendation.movie:type_name -> movieservice.v1.Movie
	8,  // 3: analytics.v1.GenerateRecommendationsResponse.recommendations:type_name -> analytics.v1.Recommendation
	8,  // 4: analytics.v1.GetRecommendationHistoryResponse.recommendations:type_name -> analytics.v1.Recommendation
	1,  // 5: analytics.v1.FeedbackService.UpsertFeedback:input_type -> analytics.v1.UpsertFeedbackRequest
	3,  // 6: analytics.v1.FeedbackService.RemoveFeedback:input_type -> analytics.v1.RemoveFeedbackRequest
	4,  // 7: analytics.v1.FeedbackService.GetFeedback:input_type -> analytics.v1.GetFeedbackRequest
	6,  // 8: analytics.v1.FeedbackService.ListUserFeedback:input_type -> analytics.v1.ListUserFeedbackRequest
	9,  // 9: analytics.v1.RecommendationService.GenerateRecommendations:input_type -> analytics.v1.GenerateRecommendationsRequest
	11, // 10: analytics.v1.RecommendationService.MarkInteraction:input_type -> analytics.v1.MarkInteractionRequest
	12, // 11: analytics.v1.RecommendationService.ResetRecommendationHistory:input_type -> analytics.v1.ResetRecommendationHistoryRequest
	13, // 12: analytics.v1.RecommendationService.GetRecommendationHistory:input_type -> analytics.v1.GetRecommendationHistoryRequest
	2,  // 13: analytics.v1.FeedbackService.UpsertFeedback:output_type -> analytics.v1.UpsertFeedbackResponse
	16, // 14: analytics.v1.FeedbackService.RemoveFeedback:output_type -> google.protobuf.Empty
	5,  // 15: analytics.v1.FeedbackService.GetFeedback:output_type -> analytics.v1.GetFeedbackResponse
	7,  // 16: analytics.v1.FeedbackService.ListUserFeedback:output_type -> analytics.v1.ListUserFeedbackResponse
	10, // 17: analytics.v1.RecommendationService.GenerateRecommendations:output_type -> analytics.v1.GenerateRecommendationsResponse
	16, // 18: analytics.v1.RecommendationService.MarkInteraction:output_type -> google.protobuf.Empty
	16, // 19: analytics.v1.RecommendationService.ResetRecommendationHistory:output_type -> google.protobuf.Empty
	14, // 20: analytics.v1.RecommendationService.GetRecommendationHistory:output_type -> analytics.v1.GetRecommendationHistoryResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_analytics_service_analytics_service_proto_init() }
func file_analytics_service_analytics_service_proto_init() {
	if File_analytics_service_analytics_service_proto != nil {
		return
	}
	file_analytics_service_analytics_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_analytics_service_analytics_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_analytics_service_analytics_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_service_analytics_service_proto_rawDesc), len(file_analytics_service_analytics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_analytics_service_analytics_service_proto_goTypes,
		DependencyIndexes: file_analytics_service_analytics_service_proto_depIdxs,
		MessageInfos:      file_analytics_service_analytics_service_proto_msgTypes,
	}.Build()
	File_analytics_service_analytics_service_proto = out.File
	file_analytics_service_analytics_service_proto_goTypes = nil
	file_analytics_service_analytics_service_proto_depIdxs = nil
}
