// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: movie_service.proto

package movieservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieService_GetMovieByID_FullMethodName = "/movieservice.v1.MovieService/GetMovieByID"
	MovieService_ListMovies_FullMethodName   = "/movieservice.v1.MovieService/ListMovies"
)

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieServiceClient interface {
	GetMovieByID(ctx context.Context, in *GetMovieByIDRequest, opts ...grpc.CallOption) (*GetMovieByIDResponse, error)
	ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) GetMovieByID(ctx context.Context, in *GetMovieByIDRequest, opts ...grpc.CallOption) (*GetMovieByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieByIDResponse)
	err := c.cc.Invoke(ctx, MovieService_GetMovieByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMoviesResponse)
	err := c.cc.Invoke(ctx, MovieService_ListMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
// All implementations must embed UnimplementedMovieServiceServer
// for forward compatibility.
type MovieServiceServer interface {
	GetMovieByID(context.Context, *GetMovieByIDRequest) (*GetMovieByIDResponse, error)
	ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error)
	mustEmbedUnimplementedMovieServiceServer()
}

// UnimplementedMovieServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieServiceServer struct{}

func (UnimplementedMovieServiceServer) GetMovieByID(context.Context, *GetMovieByIDRequest) (*GetMovieByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovieByID not implemented")
}
func (UnimplementedMovieServiceServer) ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovies not implemented")
}
func (UnimplementedMovieServiceServer) mustEmbedUnimplementedMovieServiceServer() {}
func (UnimplementedMovieServiceServer) testEmbeddedByValue()                      {}

// UnsafeMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServiceServer will
// result in compilation errors.
type UnsafeMovieServiceServer interface {
	mustEmbedUnimplementedMovieServiceServer()
}

func RegisterMovieServiceServer(s grpc.ServiceRegistrar, srv MovieServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieService_ServiceDesc, srv)
}

func _MovieService_GetMovieByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetMovieByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_GetMovieByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetMovieByID(ctx, req.(*GetMovieByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_ListMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ListMovies(ctx, req.(*ListMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieService_ServiceDesc is the grpc.ServiceDesc for MovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movieservice.v1.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovieByID",
			Handler:    _MovieService_GetMovieByID_Handler,
		},
		{
			MethodName: "ListMovies",
			Handler:    _MovieService_ListMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie_service.proto",
}

const (
	MovieAdminService_UpsertMovie_FullMethodName  = "/movieservice.v1.MovieAdminService/UpsertMovie"
	MovieAdminService_ArchiveMovie_FullMethodName = "/movieservice.v1.MovieAdminService/ArchiveMovie"
	MovieAdminService_RemoveMovie_FullMethodName  = "/movieservice.v1.MovieAdminService/RemoveMovie"
)

// MovieAdminServiceClient is the client API for MovieAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieAdminServiceClient interface {
	UpsertMovie(ctx context.Context, in *UpsertMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ArchiveMovie(ctx context.Context, in *ArchiveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type movieAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieAdminServiceClient(cc grpc.ClientConnInterface) MovieAdminServiceClient {
	return &movieAdminServiceClient{cc}
}

func (c *movieAdminServiceClient) UpsertMovie(ctx context.Context, in *UpsertMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieAdminService_UpsertMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieAdminServiceClient) ArchiveMovie(ctx context.Context, in *ArchiveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieAdminService_ArchiveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieAdminServiceClient) RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieAdminService_RemoveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieAdminServiceServer is the server API for MovieAdminService service.
// All implementations must embed UnimplementedMovieAdminServiceServer
// for forward compatibility.
type MovieAdminServiceServer interface {
	UpsertMovie(context.Context, *UpsertMovieRequest) (*emptypb.Empty, error)
	ArchiveMovie(context.Context, *ArchiveMovieRequest) (*emptypb.Empty, error)
	RemoveMovie(context.Context, *RemoveMovieRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMovieAdminServiceServer()
}

// UnimplementedMovieAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieAdminServiceServer struct{}

func (UnimplementedMovieAdminServiceServer) UpsertMovie(context.Context, *UpsertMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertMovie not implemented")
}
func (UnimplementedMovieAdminServiceServer) ArchiveMovie(context.Context, *ArchiveMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveMovie not implemented")
}
func (UnimplementedMovieAdminServiceServer) RemoveMovie(context.Context, *RemoveMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMovie not implemented")
}
func (UnimplementedMovieAdminServiceServer) mustEmbedUnimplementedMovieAdminServiceServer() {}
func (UnimplementedMovieAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeMovieAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieAdminServiceServer will
// result in compilation errors.
type UnsafeMovieAdminServiceServer interface {
	mustEmbedUnimplementedMovieAdminServiceServer()
}

func RegisterMovieAdminServiceServer(s grpc.ServiceRegistrar, srv MovieAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieAdminService_ServiceDesc, srv)
}

func _MovieAdminService_UpsertMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieAdminServiceServer).UpsertMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieAdminService_UpsertMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieAdminServiceServer).UpsertMovie(ctx, req.(*UpsertMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieAdminService_ArchiveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieAdminServiceServer).ArchiveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieAdminService_ArchiveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieAdminServiceServer).ArchiveMovie(ctx, req.(*ArchiveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieAdminService_RemoveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieAdminServiceServer).RemoveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieAdminService_RemoveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieAdminServiceServer).RemoveMovie(ctx, req.(*RemoveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieAdminService_ServiceDesc is the grpc.ServiceDesc for MovieAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movieservice.v1.MovieAdminService",
	HandlerType: (*MovieAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertMovie",
			Handler:    _MovieAdminService_UpsertMovie_Handler,
		},
		{
			MethodName: "ArchiveMovie",
			Handler:    _MovieAdminService_ArchiveMovie_Handler,
		},
		{
			MethodName: "RemoveMovie",
			Handler:    _MovieAdminService_RemoveMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie_service.proto",
}

const (
	WatchlistService_AddMovieToWatchlist_FullMethodName      = "/movieservice.v1.WatchlistService/AddMovieToWatchlist"
	WatchlistService_RemoveMovieFromWatchlist_FullMethodName = "/movieservice.v1.WatchlistService/RemoveMovieFromWatchlist"
	WatchlistService_GetUserWatchlist_FullMethodName         = "/movieservice.v1.WatchlistService/GetUserWatchlist"
)

// WatchlistServiceClient is the client API for WatchlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchlistServiceClient interface {
	AddMovieToWatchlist(ctx context.Context, in *AddMovieToWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveMovieFromWatchlist(ctx context.Context, in *RemoveMovieFromWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserWatchlist(ctx context.Context, in *GetUserWatchlistRequest, opts ...grpc.CallOption) (*GetUserWatchlistResponse, error)
}

type watchlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchlistServiceClient(cc grpc.ClientConnInterface) WatchlistServiceClient {
	return &watchlistServiceClient{cc}
}

func (c *watchlistServiceClient) AddMovieToWatchlist(ctx context.Context, in *AddMovieToWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WatchlistService_AddMovieToWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) RemoveMovieFromWatchlist(ctx context.Context, in *RemoveMovieFromWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WatchlistService_RemoveMovieFromWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) GetUserWatchlist(ctx context.Context, in *GetUserWatchlistRequest, opts ...grpc.CallOption) (*GetUserWatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserWatchlistResponse)
	err := c.cc.Invoke(ctx, WatchlistService_GetUserWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchlistServiceServer is the server API for WatchlistService service.
// All implementations must embed UnimplementedWatchlistServiceServer
// for forward compatibility.
type WatchlistServiceServer interface {
	AddMovieToWatchlist(context.Context, *AddMovieToWatchlistRequest) (*emptypb.Empty, error)
	RemoveMovieFromWatchlist(context.Context, *RemoveMovieFromWatchlistRequest) (*emptypb.Empty, error)
	GetUserWatchlist(context.Context, *GetUserWatchlistRequest) (*GetUserWatchlistResponse, error)
	mustEmbedUnimplementedWatchlistServiceServer()
}

// UnimplementedWatchlistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchlistServiceServer struct{}

func (UnimplementedWatchlistServiceServer) AddMovieToWatchlist(context.Context, *AddMovieToWatchlistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMovieToWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) RemoveMovieFromWatchlist(context.Context, *RemoveMovieFromWatchlistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMovieFromWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) GetUserWatchlist(context.Context, *GetUserWatchlistRequest) (*GetUserWatchlistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) mustEmbedUnimplementedWatchlistServiceServer() {}
func (UnimplementedWatchlistServiceServer) testEmbeddedByValue()                          {}

// UnsafeWatchlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchlistServiceServer will
// result in compilation errors.
type UnsafeWatchlistServiceServer interface {
	mustEmbedUnimplementedWatchlistServiceServer()
}

func RegisterWatchlistServiceServer(s grpc.ServiceRegistrar, srv WatchlistServiceServer) {
	// If the following call panics, it indicates UnimplementedWatchlistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchlistService_ServiceDesc, srv)
}

func _WatchlistService_AddMovieToWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMovieToWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).AddMovieToWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_AddMovieToWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).AddMovieToWatchlist(ctx, req.(*AddMovieToWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_RemoveMovieFromWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieFromWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).RemoveMovieFromWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_RemoveMovieFromWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).RemoveMovieFromWatchlist(ctx, req.(*RemoveMovieFromWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_GetUserWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).GetUserWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_GetUserWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).GetUserWatchlist(ctx, req.(*GetUserWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchlistService_ServiceDesc is the grpc.ServiceDesc for WatchlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movieservice.v1.WatchlistService",
	HandlerType: (*WatchlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMovieToWatchlist",
			Handler:    _WatchlistService_AddMovieToWatchlist_Handler,
		},
		{
			MethodName: "RemoveMovieFromWatchlist",
			Handler:    _WatchlistService_RemoveMovieFromWatchlist_Handler,
		},
		{
			MethodName: "GetUserWatchlist",
			Handler:    _WatchlistService_GetUserWatchlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie_service.proto",
}
