// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/proto/movie_collection.proto

package moviecollectionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieCatalogService_GetMovieByID_FullMethodName = "/moviecollection.v1.MovieCatalogService/GetMovieByID"
	MovieCatalogService_ListMovies_FullMethodName   = "/moviecollection.v1.MovieCatalogService/ListMovies"
)

// MovieCatalogServiceClient is the client API for MovieCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieCatalogServiceClient interface {
	GetMovieByID(ctx context.Context, in *GetMovieByIDRequest, opts ...grpc.CallOption) (*GetMovieByIDResponse, error)
	ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error)
}

type movieCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieCatalogServiceClient(cc grpc.ClientConnInterface) MovieCatalogServiceClient {
	return &movieCatalogServiceClient{cc}
}

func (c *movieCatalogServiceClient) GetMovieByID(ctx context.Context, in *GetMovieByIDRequest, opts ...grpc.CallOption) (*GetMovieByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieByIDResponse)
	err := c.cc.Invoke(ctx, MovieCatalogService_GetMovieByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieCatalogServiceClient) ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMoviesResponse)
	err := c.cc.Invoke(ctx, MovieCatalogService_ListMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieCatalogServiceServer is the server API for MovieCatalogService service.
// All implementations must embed UnimplementedMovieCatalogServiceServer
// for forward compatibility.
type MovieCatalogServiceServer interface {
	GetMovieByID(context.Context, *GetMovieByIDRequest) (*GetMovieByIDResponse, error)
	ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error)
	mustEmbedUnimplementedMovieCatalogServiceServer()
}

// UnimplementedMovieCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieCatalogServiceServer struct{}

func (UnimplementedMovieCatalogServiceServer) GetMovieByID(context.Context, *GetMovieByIDRequest) (*GetMovieByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieByID not implemented")
}
func (UnimplementedMovieCatalogServiceServer) ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMovies not implemented")
}
func (UnimplementedMovieCatalogServiceServer) mustEmbedUnimplementedMovieCatalogServiceServer() {}
func (UnimplementedMovieCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeMovieCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieCatalogServiceServer will
// result in compilation errors.
type UnsafeMovieCatalogServiceServer interface {
	mustEmbedUnimplementedMovieCatalogServiceServer()
}

func RegisterMovieCatalogServiceServer(s grpc.ServiceRegistrar, srv MovieCatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedMovieCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieCatalogService_ServiceDesc, srv)
}

func _MovieCatalogService_GetMovieByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieCatalogServiceServer).GetMovieByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieCatalogService_GetMovieByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieCatalogServiceServer).GetMovieByID(ctx, req.(*GetMovieByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieCatalogService_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieCatalogServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieCatalogService_ListMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieCatalogServiceServer).ListMovies(ctx, req.(*ListMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieCatalogService_ServiceDesc is the grpc.ServiceDesc for MovieCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviecollection.v1.MovieCatalogService",
	HandlerType: (*MovieCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovieByID",
			Handler:    _MovieCatalogService_GetMovieByID_Handler,
		},
		{
			MethodName: "ListMovies",
			Handler:    _MovieCatalogService_ListMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/movie_collection.proto",
}

const (
	MovieCatalogAdminService_UpsertMovie_FullMethodName  = "/moviecollection.v1.MovieCatalogAdminService/UpsertMovie"
	MovieCatalogAdminService_ArchiveMovie_FullMethodName = "/moviecollection.v1.MovieCatalogAdminService/ArchiveMovie"
	MovieCatalogAdminService_RemoveMovie_FullMethodName  = "/moviecollection.v1.MovieCatalogAdminService/RemoveMovie"
)

// MovieCatalogAdminServiceClient is the client API for MovieCatalogAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieCatalogAdminServiceClient interface {
	UpsertMovie(ctx context.Context, in *UpsertMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ArchiveMovie(ctx context.Context, in *ArchiveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type movieCatalogAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieCatalogAdminServiceClient(cc grpc.ClientConnInterface) MovieCatalogAdminServiceClient {
	return &movieCatalogAdminServiceClient{cc}
}

func (c *movieCatalogAdminServiceClient) UpsertMovie(ctx context.Context, in *UpsertMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieCatalogAdminService_UpsertMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieCatalogAdminServiceClient) ArchiveMovie(ctx context.Context, in *ArchiveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieCatalogAdminService_ArchiveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieCatalogAdminServiceClient) RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MovieCatalogAdminService_RemoveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieCatalogAdminServiceServer is the server API for MovieCatalogAdminService service.
// All implementations must embed UnimplementedMovieCatalogAdminServiceServer
// for forward compatibility.
type MovieCatalogAdminServiceServer interface {
	UpsertMovie(context.Context, *UpsertMovieRequest) (*emptypb.Empty, error)
	ArchiveMovie(context.Context, *ArchiveMovieRequest) (*emptypb.Empty, error)
	RemoveMovie(context.Context, *RemoveMovieRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMovieCatalogAdminServiceServer()
}

// UnimplementedMovieCatalogAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieCatalogAdminServiceServer struct{}

func (UnimplementedMovieCatalogAdminServiceServer) UpsertMovie(context.Context, *UpsertMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMovie not implemented")
}
func (UnimplementedMovieCatalogAdminServiceServer) ArchiveMovie(context.Context, *ArchiveMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveMovie not implemented")
}
func (UnimplementedMovieCatalogAdminServiceServer) RemoveMovie(context.Context, *RemoveMovieRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMovie not implemented")
}
func (UnimplementedMovieCatalogAdminServiceServer) mustEmbedUnimplementedMovieCatalogAdminServiceServer() {
}
func (UnimplementedMovieCatalogAdminServiceServer) testEmbeddedByValue() {}

// UnsafeMovieCatalogAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieCatalogAdminServiceServer will
// result in compilation errors.
type UnsafeMovieCatalogAdminServiceServer interface {
	mustEmbedUnimplementedMovieCatalogAdminServiceServer()
}

func RegisterMovieCatalogAdminServiceServer(s grpc.ServiceRegistrar, srv MovieCatalogAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedMovieCatalogAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieCatalogAdminService_ServiceDesc, srv)
}

func _MovieCatalogAdminService_UpsertMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieCatalogAdminServiceServer).UpsertMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieCatalogAdminService_UpsertMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieCatalogAdminServiceServer).UpsertMovie(ctx, req.(*UpsertMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieCatalogAdminService_ArchiveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieCatalogAdminServiceServer).ArchiveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieCatalogAdminService_ArchiveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieCatalogAdminServiceServer).ArchiveMovie(ctx, req.(*ArchiveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieCatalogAdminService_RemoveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieCatalogAdminServiceServer).RemoveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieCatalogAdminService_RemoveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieCatalogAdminServiceServer).RemoveMovie(ctx, req.(*RemoveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieCatalogAdminService_ServiceDesc is the grpc.ServiceDesc for MovieCatalogAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieCatalogAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviecollection.v1.MovieCatalogAdminService",
	HandlerType: (*MovieCatalogAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertMovie",
			Handler:    _MovieCatalogAdminService_UpsertMovie_Handler,
		},
		{
			MethodName: "ArchiveMovie",
			Handler:    _MovieCatalogAdminService_ArchiveMovie_Handler,
		},
		{
			MethodName: "RemoveMovie",
			Handler:    _MovieCatalogAdminService_RemoveMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/movie_collection.proto",
}

const (
	WatchlistService_AddMovieToWatchlist_FullMethodName      = "/moviecollection.v1.WatchlistService/AddMovieToWatchlist"
	WatchlistService_RemoveMovieFromWatchlist_FullMethodName = "/moviecollection.v1.WatchlistService/RemoveMovieFromWatchlist"
	WatchlistService_GetWatchlist_FullMethodName             = "/moviecollection.v1.WatchlistService/GetWatchlist"
)

// WatchlistServiceClient is the client API for WatchlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchlistServiceClient interface {
	AddMovieToWatchlist(ctx context.Context, in *AddMovieToWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveMovieFromWatchlist(ctx context.Context, in *RemoveMovieFromWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWatchlist(ctx context.Context, in *GetWatchlistRequest, opts ...grpc.CallOption) (*GetWatchlistResponse, error)
}

type watchlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchlistServiceClient(cc grpc.ClientConnInterface) WatchlistServiceClient {
	return &watchlistServiceClient{cc}
}

func (c *watchlistServiceClient) AddMovieToWatchlist(ctx context.Context, in *AddMovieToWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WatchlistService_AddMovieToWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) RemoveMovieFromWatchlist(ctx context.Context, in *RemoveMovieFromWatchlistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WatchlistService_RemoveMovieFromWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) GetWatchlist(ctx context.Context, in *GetWatchlistRequest, opts ...grpc.CallOption) (*GetWatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatchlistResponse)
	err := c.cc.Invoke(ctx, WatchlistService_GetWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchlistServiceServer is the server API for WatchlistService service.
// All implementations must embed UnimplementedWatchlistServiceServer
// for forward compatibility.
type WatchlistServiceServer interface {
	AddMovieToWatchlist(context.Context, *AddMovieToWatchlistRequest) (*emptypb.Empty, error)
	RemoveMovieFromWatchlist(context.Context, *RemoveMovieFromWatchlistRequest) (*emptypb.Empty, error)
	GetWatchlist(context.Context, *GetWatchlistRequest) (*GetWatchlistResponse, error)
	mustEmbedUnimplementedWatchlistServiceServer()
}

// UnimplementedWatchlistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchlistServiceServer struct{}

func (UnimplementedWatchlistServiceServer) AddMovieToWatchlist(context.Context, *AddMovieToWatchlistRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMovieToWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) RemoveMovieFromWatchlist(context.Context, *RemoveMovieFromWatchlistRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMovieFromWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) GetWatchlist(context.Context, *GetWatchlistRequest) (*GetWatchlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) mustEmbedUnimplementedWatchlistServiceServer() {}
func (UnimplementedWatchlistServiceServer) testEmbeddedByValue()                          {}

// UnsafeWatchlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchlistServiceServer will
// result in compilation errors.
type UnsafeWatchlistServiceServer interface {
	mustEmbedUnimplementedWatchlistServiceServer()
}

func RegisterWatchlistServiceServer(s grpc.ServiceRegistrar, srv WatchlistServiceServer) {
	// If the following call pancis, it indicates UnimplementedWatchlistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchlistService_ServiceDesc, srv)
}

func _WatchlistService_AddMovieToWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMovieToWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).AddMovieToWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_AddMovieToWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).AddMovieToWatchlist(ctx, req.(*AddMovieToWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_RemoveMovieFromWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieFromWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).RemoveMovieFromWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_RemoveMovieFromWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).RemoveMovieFromWatchlist(ctx, req.(*RemoveMovieFromWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_GetWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).GetWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_GetWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).GetWatchlist(ctx, req.(*GetWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchlistService_ServiceDesc is the grpc.ServiceDesc for WatchlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviecollection.v1.WatchlistService",
	HandlerType: (*WatchlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMovieToWatchlist",
			Handler:    _WatchlistService_AddMovieToWatchlist_Handler,
		},
		{
			MethodName: "RemoveMovieFromWatchlist",
			Handler:    _WatchlistService_RemoveMovieFromWatchlist_Handler,
		},
		{
			MethodName: "GetWatchlist",
			Handler:    _WatchlistService_GetWatchlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/movie_collection.proto",
}
