syntax = "proto3";

package proto;

option go_package = "./;proto";

service UserCollectionService {
  rpc AddToWatchlist(AddToWatchlistRequest) returns (AddToWatchlistResponse);
  rpc MarkAsWatched(MarkAsWatchedRequest) returns (MarkAsWatchedResponse);
  rpc RateMovie(RateMovieRequest) returns (RateMovieResponse);
  rpc ReviewMovie(ReviewMovieRequest) returns (ReviewMovieResponse);
  rpc GetUserCollection(GetUserCollectionRequest) returns (GetUserCollectionResponse);
}

message AddToWatchlistRequest {
  int64 user_id = 1;
  int64 movie_id = 2;
}

message AddToWatchlistResponse {
  string message = 1;
}

message MarkAsWatchedRequest {
  int64 user_id = 1;
  int64 movie_id = 2;
}

message MarkAsWatchedResponse {
  string message = 1;
}

message RateMovieRequest {
  int64 user_id = 1;
  int64 movie_id = 2;
  int32 rating = 3;
}

message RateMovieResponse {
  string message = 1;
}

message ReviewMovieRequest {
  int64 user_id = 1;
  int64 movie_id = 2;
  string review = 3;
}

message ReviewMovieResponse {
  string message = 1;
}

message GetUserCollectionRequest {
  int64 user_id = 1;
}

message UserCollectionItem {
  int64 movie_id = 1;
  string title = 2;
  bool in_watchlist = 3;
  bool watched = 4;
  int32 rating = 5;
  string review = 6;
}

message GetUserCollectionResponse {
  repeated UserCollectionItem items = 1;
}
