version: "3.9"

services:
  social-service:
    build: .
    command: ["/social-service", "-config", "configs/config.docker.yaml"]
    environment:
      - SOCIAL_DATABASE_URL=postgres://social:socialpassword@postgres:5432/socialdb?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "50053:50053"
    networks:
      - social-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: socialpassword
      POSTGRES_DB: socialdb
    volumes:
      - social_postgres_data:/var/lib/postgresql/data
    networks:
      - social-network

volumes:
  social_postgres_data:

networks:
  social-network:
    driver: bridge
