// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: movie_collection.proto

package moviecollectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Actors        []*Person              `protobuf:"bytes,5,rep,name=actors,proto3" json:"actors,omitempty"`
	Directors     []*Person              `protobuf:"bytes,6,rep,name=directors,proto3" json:"directors,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,8,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	ImdbRating    float32                `protobuf:"fixed32,9,opt,name=imdb_rating,json=imdbRating,proto3" json:"imdb_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Movie) GetActors() []*Person {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *Movie) GetDirectors() []*Person {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *Movie) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Movie) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Movie) GetImdbRating() float32 {
	if x != nil {
		return x.ImdbRating
	}
	return 0
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_movie_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{1}
}

func (x *Genre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	BirthYear     *int32                 `protobuf:"varint,4,opt,name=birth_year,json=birthYear,proto3,oneof" json:"birth_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_movie_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{2}
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Person) GetBirthYear() int32 {
	if x != nil && x.BirthYear != nil {
		return *x.BirthYear
	}
	return 0
}

type GetMovieByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIDRequest) Reset() {
	*x = GetMovieByIDRequest{}
	mi := &file_movie_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIDRequest) ProtoMessage() {}

func (x *GetMovieByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMovieByIDRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieByIDRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIDResponse) Reset() {
	*x = GetMovieByIDResponse{}
	mi := &file_movie_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIDResponse) ProtoMessage() {}

func (x *GetMovieByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMovieByIDResponse) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieByIDResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type ListMoviesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Genres          []*Genre               `protobuf:"bytes,2,rep,name=genres,proto3" json:"genres,omitempty"`
	Actors          []*Person              `protobuf:"bytes,3,rep,name=actors,proto3" json:"actors,omitempty"`
	Directors       []*Person              `protobuf:"bytes,4,rep,name=directors,proto3" json:"directors,omitempty"`
	Country         *string                `protobuf:"bytes,5,opt,name=country,proto3,oneof" json:"country,omitempty"`
	ReleaseYearFrom *int32                 `protobuf:"varint,6,opt,name=release_year_from,json=releaseYearFrom,proto3,oneof" json:"release_year_from,omitempty"`
	ReleaseYearTo   *int32                 `protobuf:"varint,7,opt,name=release_year_to,json=releaseYearTo,proto3,oneof" json:"release_year_to,omitempty"`
	ImdbRatingFrom  *float32               `protobuf:"fixed32,8,opt,name=imdb_rating_from,json=imdbRatingFrom,proto3,oneof" json:"imdb_rating_from,omitempty"`
	ImdbRatingTo    *float32               `protobuf:"fixed32,9,opt,name=imdb_rating_to,json=imdbRatingTo,proto3,oneof" json:"imdb_rating_to,omitempty"`
	Limit           int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy          string                 `protobuf:"bytes,12,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder       string                 `protobuf:"bytes,13,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,14,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMoviesRequest) Reset() {
	*x = ListMoviesRequest{}
	mi := &file_movie_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesRequest) ProtoMessage() {}

func (x *ListMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesRequest.ProtoReflect.Descriptor instead.
func (*ListMoviesRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{5}
}

func (x *ListMoviesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListMoviesRequest) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *ListMoviesRequest) GetActors() []*Person {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *ListMoviesRequest) GetDirectors() []*Person {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *ListMoviesRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *ListMoviesRequest) GetReleaseYearFrom() int32 {
	if x != nil && x.ReleaseYearFrom != nil {
		return *x.ReleaseYearFrom
	}
	return 0
}

func (x *ListMoviesRequest) GetReleaseYearTo() int32 {
	if x != nil && x.ReleaseYearTo != nil {
		return *x.ReleaseYearTo
	}
	return 0
}

func (x *ListMoviesRequest) GetImdbRatingFrom() float32 {
	if x != nil && x.ImdbRatingFrom != nil {
		return *x.ImdbRatingFrom
	}
	return 0
}

func (x *ListMoviesRequest) GetImdbRatingTo() float32 {
	if x != nil && x.ImdbRatingTo != nil {
		return *x.ImdbRatingTo
	}
	return 0
}

func (x *ListMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMoviesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMoviesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListMoviesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListMoviesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesResponse) Reset() {
	*x = ListMoviesResponse{}
	mi := &file_movie_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesResponse) ProtoMessage() {}

func (x *ListMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesResponse.ProtoReflect.Descriptor instead.
func (*ListMoviesResponse) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{6}
}

func (x *ListMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type UpsertMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMovieRequest) Reset() {
	*x = UpsertMovieRequest{}
	mi := &file_movie_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMovieRequest) ProtoMessage() {}

func (x *UpsertMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMovieRequest.ProtoReflect.Descriptor instead.
func (*UpsertMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertMovieRequest) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type ArchiveMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveMovieRequest) Reset() {
	*x = ArchiveMovieRequest{}
	mi := &file_movie_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveMovieRequest) ProtoMessage() {}

func (x *ArchiveMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveMovieRequest.ProtoReflect.Descriptor instead.
func (*ArchiveMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type RemoveMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMovieRequest) Reset() {
	*x = RemoveMovieRequest{}
	mi := &file_movie_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieRequest) ProtoMessage() {}

func (x *RemoveMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieRequest.ProtoReflect.Descriptor instead.
func (*RemoveMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type AddMovieToWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMovieToWatchlistRequest) Reset() {
	*x = AddMovieToWatchlistRequest{}
	mi := &file_movie_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMovieToWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieToWatchlistRequest) ProtoMessage() {}

func (x *AddMovieToWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieToWatchlistRequest.ProtoReflect.Descriptor instead.
func (*AddMovieToWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{10}
}

func (x *AddMovieToWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMovieToWatchlistRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type RemoveMovieFromWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMovieFromWatchlistRequest) Reset() {
	*x = RemoveMovieFromWatchlistRequest{}
	mi := &file_movie_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMovieFromWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieFromWatchlistRequest) ProtoMessage() {}

func (x *RemoveMovieFromWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieFromWatchlistRequest.ProtoReflect.Descriptor instead.
func (*RemoveMovieFromWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveMovieFromWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveMovieFromWatchlistRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetUserWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWatchlistRequest) Reset() {
	*x = GetUserWatchlistRequest{}
	mi := &file_movie_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWatchlistRequest) ProtoMessage() {}

func (x *GetUserWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWatchlistRequest.ProtoReflect.Descriptor instead.
func (*GetUserWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWatchlistResponse) Reset() {
	*x = GetUserWatchlistResponse{}
	mi := &file_movie_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWatchlistResponse) ProtoMessage() {}

func (x *GetUserWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWatchlistResponse.ProtoReflect.Descriptor instead.
func (*GetUserWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_movie_collection_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserWatchlistResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_movie_collection_proto protoreflect.FileDescriptor

const file_movie_collection_proto_rawDesc = "" +
	"\n" +
	"\x16movie_collection.proto\x12\x12moviecollection.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x02\n" +
	"\x05Movie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x06genres\x18\x04 \x03(\v2\x19.moviecollection.v1.GenreR\x06genres\x122\n" +
	"\x06actors\x18\x05 \x03(\v2\x1a.moviecollection.v1.PersonR\x06actors\x128\n" +
	"\tdirectors\x18\x06 \x03(\v2\x1a.moviecollection.v1.PersonR\tdirectors\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12!\n" +
	"\frelease_year\x18\b \x01(\x05R\vreleaseYear\x12\x1f\n" +
	"\vimdb_rating\x18\t \x01(\x02R\n" +
	"imdbRating\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"y\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12\"\n" +
	"\n" +
	"birth_year\x18\x04 \x01(\x05H\x00R\tbirthYear\x88\x01\x01B\r\n" +
	"\v_birth_year\"0\n" +
	"\x13GetMovieByIDRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"G\n" +
	"\x14GetMovieByIDResponse\x12/\n" +
	"\x05movie\x18\x01 \x01(\v2\x19.moviecollection.v1.MovieR\x05movie\"\x90\x05\n" +
	"\x11ListMoviesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x121\n" +
	"\x06genres\x18\x02 \x03(\v2\x19.moviecollection.v1.GenreR\x06genres\x122\n" +
	"\x06actors\x18\x03 \x03(\v2\x1a.moviecollection.v1.PersonR\x06actors\x128\n" +
	"\tdirectors\x18\x04 \x03(\v2\x1a.moviecollection.v1.PersonR\tdirectors\x12\x1d\n" +
	"\acountry\x18\x05 \x01(\tH\x00R\acountry\x88\x01\x01\x12/\n" +
	"\x11release_year_from\x18\x06 \x01(\x05H\x01R\x0freleaseYearFrom\x88\x01\x01\x12+\n" +
	"\x0frelease_year_to\x18\a \x01(\x05H\x02R\rreleaseYearTo\x88\x01\x01\x12-\n" +
	"\x10imdb_rating_from\x18\b \x01(\x02H\x03R\x0eimdbRatingFrom\x88\x01\x01\x12)\n" +
	"\x0eimdb_rating_to\x18\t \x01(\x02H\x04R\fimdbRatingTo\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\v \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\f \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\r \x01(\tR\tsortOrder\x12)\n" +
	"\x10include_archived\x18\x0e \x01(\bR\x0fincludeArchivedB\n" +
	"\n" +
	"\b_countryB\x14\n" +
	"\x12_release_year_fromB\x12\n" +
	"\x10_release_year_toB\x13\n" +
	"\x11_imdb_rating_fromB\x11\n" +
	"\x0f_imdb_rating_to\"G\n" +
	"\x12ListMoviesResponse\x121\n" +
	"\x06movies\x18\x01 \x03(\v2\x19.moviecollection.v1.MovieR\x06movies\"E\n" +
	"\x12UpsertMovieRequest\x12/\n" +
	"\x05movie\x18\x01 \x01(\v2\x19.moviecollection.v1.MovieR\x05movie\"0\n" +
	"\x13ArchiveMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"/\n" +
	"\x12RemoveMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"P\n" +
	"\x1aAddMovieToWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\"U\n" +
	"\x1fRemoveMovieFromWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\"2\n" +
	"\x17GetUserWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x18GetUserWatchlistResponse\x121\n" +
	"\x06movies\x18\x01 \x03(\v2\x19.moviecollection.v1.MovieR\x06movies2\xd5\x01\n" +
	"\x13MovieCatalogService\x12a\n" +
	"\fGetMovieByID\x12'.moviecollection.v1.GetMovieByIDRequest\x1a(.moviecollection.v1.GetMovieByIDResponse\x12[\n" +
	"\n" +
	"ListMovies\x12%.moviecollection.v1.ListMoviesRequest\x1a&.moviecollection.v1.ListMoviesResponse2\x89\x02\n" +
	"\x18MovieCatalogAdminService\x12M\n" +
	"\vUpsertMovie\x12&.moviecollection.v1.UpsertMovieRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\fArchiveMovie\x12'.moviecollection.v1.ArchiveMovieRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\vRemoveMovie\x12&.moviecollection.v1.RemoveMovieRequest\x1a\x16.google.protobuf.Empty2\xc9\x02\n" +
	"\x10WatchlistService\x12]\n" +
	"\x13AddMovieToWatchlist\x12..moviecollection.v1.AddMovieToWatchlistRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x18RemoveMovieFromWatchlist\x123.moviecollection.v1.RemoveMovieFromWatchlistRequest\x1a\x16.google.protobuf.Empty\x12m\n" +
	"\x10GetUserWatchlist\x12+.moviecollection.v1.GetUserWatchlistRequest\x1a,.moviecollection.v1.GetUserWatchlistResponseBYZWgithub.com/BigMoneyBigSuccess/cineMate/proto/movies/moviecollectionv1;moviecollectionv1b\x06proto3"

var (
	file_movie_collection_proto_rawDescOnce sync.Once
	file_movie_collection_proto_rawDescData []byte
)

func file_movie_collection_proto_rawDescGZIP() []byte {
	file_movie_collection_proto_rawDescOnce.Do(func() {
		file_movie_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_collection_proto_rawDesc), len(file_movie_collection_proto_rawDesc)))
	})
	return file_movie_collection_proto_rawDescData
}

var file_movie_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_movie_collection_proto_goTypes = []any{
	(*Movie)(nil),                           // 0: moviecollection.v1.Movie
	(*Genre)(nil),                           // 1: moviecollection.v1.Genre
	(*Person)(nil),                          // 2: moviecollection.v1.Person
	(*GetMovieByIDRequest)(nil),             // 3: moviecollection.v1.GetMovieByIDRequest
	(*GetMovieByIDResponse)(nil),            // 4: moviecollection.v1.GetMovieByIDResponse
	(*ListMoviesRequest)(nil),               // 5: moviecollection.v1.ListMoviesRequest
	(*ListMoviesResponse)(nil),              // 6: moviecollection.v1.ListMoviesResponse
	(*UpsertMovieRequest)(nil),              // 7: moviecollection.v1.UpsertMovieRequest
	(*ArchiveMovieRequest)(nil),             // 8: moviecollection.v1.ArchiveMovieRequest
	(*RemoveMovieRequest)(nil),              // 9: moviecollection.v1.RemoveMovieRequest
	(*AddMovieToWatchlistRequest)(nil),      // 10: moviecollection.v1.AddMovieToWatchlistRequest
	(*RemoveMovieFromWatchlistRequest)(nil), // 11: moviecollection.v1.RemoveMovieFromWatchlistRequest
	(*GetUserWatchlistRequest)(nil),         // 12: moviecollection.v1.GetUserWatchlistRequest
	(*GetUserWatchlistResponse)(nil),        // 13: moviecollection.v1.GetUserWatchlistResponse
	(*emptypb.Empty)(nil),                   // 14: google.protobuf.Empty
}
var file_movie_collection_proto_depIdxs = []int32{
	1,  // 0: moviecollection.v1.Movie.genres:type_name -> moviecollection.v1.Genre
	2,  // 1: moviecollection.v1.Movie.actors:type_name -> moviecollection.v1.Person
	2,  // 2: moviecollection.v1.Movie.directors:type_name -> moviecollection.v1.Person
	0,  // 3: moviecollection.v1.GetMovieByIDResponse.movie:type_name -> moviecollection.v1.Movie
	1,  // 4: moviecollection.v1.ListMoviesRequest.genres:type_name -> moviecollection.v1.Genre
	2,  // 5: moviecollection.v1.ListMoviesRequest.actors:type_name -> moviecollection.v1.Person
	2,  // 6: moviecollection.v1.ListMoviesRequest.directors:type_name -> moviecollection.v1.Person
	0,  // 7: moviecollection.v1.ListMoviesResponse.movies:type_name -> moviecollection.v1.Movie
	0,  // 8: moviecollection.v1.UpsertMovieRequest.movie:type_name -> moviecollection.v1.Movie
	0,  // 9: moviecollection.v1.GetUserWatchlistResponse.movies:type_name -> moviecollection.v1.Movie
	3,  // 10: moviecollection.v1.MovieCatalogService.GetMovieByID:input_type -> moviecollection.v1.GetMovieByIDRequest
	5,  // 11: moviecollection.v1.MovieCatalogService.ListMovies:input_type -> moviecollection.v1.ListMoviesRequest
	7,  // 12: moviecollection.v1.MovieCatalogAdminService.UpsertMovie:input_type -> moviecollection.v1.UpsertMovieRequest
	8,  // 13: moviecollection.v1.MovieCatalogAdminService.ArchiveMovie:input_type -> moviecollection.v1.ArchiveMovieRequest
	9,  // 14: moviecollection.v1.MovieCatalogAdminService.RemoveMovie:input_type -> moviecollection.v1.RemoveMovieRequest
	10, // 15: moviecollection.v1.WatchlistService.AddMovieToWatchlist:input_type -> moviecollection.v1.AddMovieToWatchlistRequest
	11, // 16: moviecollection.v1.WatchlistService.RemoveMovieFromWatchlist:input_type -> moviecollection.v1.RemoveMovieFromWatchlistRequest
	12, // 17: moviecollection.v1.WatchlistService.GetUserWatchlist:input_type -> moviecollection.v1.GetUserWatchlistRequest
	4,  // 18: moviecollection.v1.MovieCatalogService.GetMovieByID:output_type -> moviecollection.v1.GetMovieByIDResponse
	6,  // 19: moviecollection.v1.MovieCatalogService.ListMovies:output_type -> moviecollection.v1.ListMoviesResponse
	14, // 20: moviecollection.v1.MovieCatalogAdminService.UpsertMovie:output_type -> google.protobuf.Empty
	14, // 21: moviecollection.v1.MovieCatalogAdminService.ArchiveMovie:output_type -> google.protobuf.Empty
	14, // 22: moviecollection.v1.MovieCatalogAdminService.RemoveMovie:output_type -> google.protobuf.Empty
	14, // 23: moviecollection.v1.WatchlistService.AddMovieToWatchlist:output_type -> google.protobuf.Empty
	14, // 24: moviecollection.v1.WatchlistService.RemoveMovieFromWatchlist:output_type -> google.protobuf.Empty
	13, // 25: moviecollection.v1.WatchlistService.GetUserWatchlist:output_type -> moviecollection.v1.GetUserWatchlistResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_movie_collection_proto_init() }
func file_movie_collection_proto_init() {
	if File_movie_collection_proto != nil {
		return
	}
	file_movie_collection_proto_msgTypes[2].OneofWrappers = []any{}
	file_movie_collection_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_collection_proto_rawDesc), len(file_movie_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_movie_collection_proto_goTypes,
		DependencyIndexes: file_movie_collection_proto_depIdxs,
		MessageInfos:      file_movie_collection_proto_msgTypes,
	}.Build()
	File_movie_collection_proto = out.File
	file_movie_collection_proto_goTypes = nil
	file_movie_collection_proto_depIdxs = nil
}
