grpc:
  addr: ":8080"

postgres:
  url: "postgres://movie_collection:movie_collection@postgres:5432/movie_collection?sslmode=disable"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

cache:
  movie_ttl: 30m
  movie_list_ttl: 2m

shutdown_timeout: 10s
